baseURL = "https://itsy.sh/"
languageCode = "en-us"
title = "itsy.sh"
theme = "anubis"



[menu]
  [[menu.main]]
    name = "blog"
    identifier = "blog"
    url = "/blog/"
    weight = 1

[taxonomies]
tag = "tags"
